### PR TITLE
Scratch Block Comments

### LINKED ISSUE #1530: Block comments don't have a context menu
Block comments have a context menu on the textarea, but not one on the border/handle of the comment that would let us have the delete option.  Do we want one?

### LINKED ISSUE #1531: Block comment should auto-open when created
### Expected Behavior
Comment auto-opens and is selected when the "add comment" option is clicked in the block's context menu.

### Actual Behavior

The comment icon is added but the user has to click on the icon to open up the comment and start editing.

### LINKED ISSUE #1548: Toolbox is broken in RTL
### Expected Behavior

Workspace renders properly in RTL

### Actual Behavior

Switching to RTL in the vertical playground fails with these errors: 
```
flyout_base.js:609 Uncaught TypeError: Cannot set property 'length' of undefined
    at Blockly.VerticalFlyout.Blockly.Flyout.recordCategoryScrollPositions_ (flyout_base.js:609)
    at Blockly.VerticalFlyout.getMetrics_ (flyout_vertical.js:211)
    at Blockly.WorkspaceSvg.getWidth (workspace_svg.js:830)
    at Object.Blockly.Xml.blockToDomWithXY (xml.js:86)
    at new Blockly.Events.Create (block_events.js:226)
    at Object.Blockly.Xml.domToBlock (xml.js:586)
    at Blockly.VerticalFlyout.Blockly.Flyout.show (flyout_base.js:506)
    at Blockly.Toolbox.showAll_ (toolbox.js:209)
    at Blockly.Toolbox.populate_ (toolbox.js:186)
    at Blockly.Toolbox.init (toolbox.js:135)
```
### Steps to Reproduce

Open the vertical playground and switch to RTL mode.

### Operating System and Browser

Any

### PR DESCRIPTION
**Pull request by kchadha**
### Resolves

Resolves the following for Scratch Block Comments:
#1529 <-- not going to close this one since it is still a problem for non scratch bubbles
#1532 <--- ""
#1528 <--- ""

Resolves #1531 
Resolves #1530 
Resolves #1548

### Proposed Changes

Add new scratch style block comments which inherit from Blockly.Comment and Blockly.Bubble.

Scratch style block comments: 
 * have no icon on the block
 * are anchored to the right side of the block
 * cannot be made 'invisible' by the user
 * can be minimized so that only the comment top bar shows (with truncated text)
 * remember their height and width before they are minimized
 * have a context menu with a delete option
 * have a delete option on the block
 * have an auto-layout if there is no explicit position provided -- this auto layout is mostly to 
    accommodate projects imported from 2.0 and is likely to change in the future.

#### Known Issues
* Workspace comments need to be updated to look/work like block comments
* Some outstanding issues with drag + text selection
* Auto layout probably needs improvement
* UI layout needs improvement (some things seem to be are off by a pixel or so...)
* Should be able to delete a block comment off of a block by dragging it to the toolbox. (needs implementation)

### Reason for Changes

Compatibility with 2.0, desired features for scratch comments, and some bug fixes.

### Test Coverage

Testing in the vertical_playground, and tested importing a project with block comments.

### CODE REVIEW

File: core/block_render_svg_vertical.js [hunk 1]
```diff
@@ -651,6 +658,13 @@ Blockly.BlockSvg.prototype.render = function(opt_bubble) {
 
   this.renderClassify_();
 
+  // Position the Scratch Block Comment Icon at the end of the block
+  if (scratchCommentIcon) {
+    var iconX = this.RTL ? -inputRows.rightEdge : inputRows.rightEdge;
```
Comment (rachel-fenichel) [inline core/block_render_svg_vertical.js:663]: Did you check that this positions it correctly in RTL?

File: core/block_svg.js [hunk 2]
```diff
@@ -980,12 +980,20 @@ Blockly.BlockSvg.prototype.getCommentText = function() {
 /**
  * Set this block's comment text.
  * @param {?string} text The text, or null to delete.
+ * @param {?string} type If 'scratch', treat as ScratchBlockComment, else Comment
+ * @param {?number} commentX Optional x position for scratch comment
```
Comment (rachel-fenichel) [inline core/block_svg.js]: If these are optional, annotate them as `{number=}` or `{type=}`.

File: core/xml.js [hunk 3]
```diff
@@ -194,7 +194,17 @@ Blockly.Xml.blockToDom = function(block, opt_noId) {
     var commentElement = goog.dom.createDom('comment', null, commentText);
     if (typeof block.comment == 'object') {
       commentElement.setAttribute('pinned', block.comment.isVisible());
-      var hw = block.comment.getBubbleSize();
+      var hw;
```
Comment (rachel-fenichel) [inline core/xml.js]: Make these into helper functions.

File: core/scratch_block_comment.js [hunk 4]
```diff
@@ -0,0 +1,404 @@
+/**
+ * @license
+ * Visual Blocks Editor
+ *
+ * Copyright 2011 Google Inc.
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: Fix year.

File: core/scratch_block_comment.js [hunk 5]
```diff
@@ -0,0 +1,404 @@
...
+/**
+ * @fileoverview Object representing a code comment.
+ * @author kchadha@scratch.mit.edu (Karishma Chadha)
+ */
+'use strict';
+
+goog.provide('Blockly.ScratchBlockComment');
+
+goog.require('Blockly.Comment');
+goog.require('Blockly.ScratchBubble');
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: Alphabetical order, and an extra space between the Blockly requires and the goog requires.

File: core/scratch_block_comment.js [hunk 6]
```diff
@@ -0,0 +1,404 @@
...
+goog.require('goog.math.Coordinate');
+
+
+/**
+ * Class for a comment.
+ * @param {!Blockly.Block} block The block associated with this comment.
+ * @param {?number} x Initial x position for comment
+ * @param {?number} y Initial y position for comment
+ * @param {?boolean} minimized Whether or not this comment is minimized
+ * (only the top bar displays), defaults to false
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: Indent line continuations +4, and add periods at end of comments.

File: core/scratch_block_comment.js [hunk 7]
```diff
@@ -0,0 +1,404 @@
...
+goog.require('Blockly.Events.Ui');
+goog.require('Blockly.Icon');
+goog.require('goog.userAgent');
+goog.require('goog.math.Coordinate');
+
+
+/**
+ * Class for a comment.
+ * @param {!Blockly.Block} block The block associated with this comment.
+ * @param {?number} x Initial x position for comment
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: Why are these all allowed to be undefined?

File: core/scratch_block_comment.js [hunk 8]
```diff
@@ -0,0 +1,404 @@
...
+/**
+ * Height of bubble.
+ * @private
+ */
+Blockly.ScratchBlockComment.prototype.height_ = 200;
+
+/**
+ * Comment Icon Size.
+ */
+Blockly.ScratchBlockComment.prototype.SIZE = 0;
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: This probably doesn't need to be on the prototype.  Also, these constants probably don't need to be public.  They are probably private, package, or protected.

File: core/scratch_block_comment.js [hunk 9]
```diff
@@ -0,0 +1,404 @@
...
+};
+
+// Override renderIcon from Blocky.Icon so that the comment bubble is
+// anchored correctly on the block. This function takes in the top margin
+// as an input instead of setting an arbitrary one.
+/**
+ * Render the icon.
+ * @param {number} cursorX Horizontal offset at which to position the icon.
+ * @param {number} topMargin Vertical offset from the top of the block to position the icon.
+ * @return {number} Horizontal offset for next item to draw.
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js:110]: @package

File: core/scratch_block_comment.js [hunk 10]
```diff
@@ -0,0 +1,404 @@
...
+    cursorX -= Blockly.BlockSvg.SEP_SPACE_X;
+  } else {
+    cursorX += width + Blockly.BlockSvg.SEP_SPACE_X;
+  }
+  return cursorX;
+};
+
+/**
+ * Create the editor for the comment's bubble.
+ * @return {!Element} The top-level node of the editor.
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: Return annotation is wrong.

File: core/scratch_block_comment.js [hunk 11]
```diff
@@ -0,0 +1,404 @@
...
+       Blockly.ScratchBubble.TOP_BAR_HEIGHT - textOffset) + 'px';
+
+    // Actually set the size!
+    this.width_ = size.width;
+    this.height_ = size.height;
+  }
+};
+
+/**
+ * Change the colour of the associated bubble to match its block.
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js:208]: @package

File: core/scratch_block_comment.js [hunk 12]
```diff
@@ -0,0 +1,404 @@
...
+    this.text_ = text;
+  }
+  if (this.textarea_) {
+    this.textarea_.value = text;
+  }
+};
+
+/**
+ * Move this comment to a position given x and y coordinates.
+ * @param {number} x The x-coordinate
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: Relative position or absolute?  If relative, relative to what?

File: core/scratch_block_comment.js [hunk 13]
```diff
@@ -0,0 +1,404 @@
...
+ * @param {number} y The y-coordinate
+ */
+Blockly.ScratchBlockComment.prototype.moveTo = function(x, y) {
+  if (this.bubble_) {
+    this.bubble_.moveTo(x, y);
+  }
+  this.x_ = x;
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js:388]: Everywhere else you're using `this.x` and `this.y`.  Here and in the next function you're using `this.x_` and `this.y_`.

File: core/scratch_block_comment.js [hunk 14]
```diff
@@ -0,0 +1,404 @@
...
+  if (this.bubble_) {
+    return this.bubble_.getRelativeToSurfaceXY();
+  } else {
+    return new goog.math.Coordinate(this.x_, this.y_);
+  }
+};
+
+/**
+ * Get the height and width of this comment.
+ * Note: this does not use the bubble XY because
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: Bubble XY doesn't give the height and width anyway.  Update or delete this comment.

File: core/scratch_block_comment.js [hunk 15]
```diff
@@ -0,0 +1,404 @@
...
+ * the bubble may be minimized.
+ * @return {{height: number, width: number}} The height and width of
+ * this comment when it is full size.
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: Indent continuation +4 spaces.

File: core/scratch_block_comment.js [hunk 16]
```diff
@@ -0,0 +1,404 @@
...
+  } else {
+    return new goog.math.Coordinate(this.x_, this.y_);
+  }
+};
+
+/**
+ * Get the height and width of this comment.
+ * Note: this does not use the bubble XY because
+ * the bubble may be minimized.
+ * @return {{height: number, width: number}} The height and width of
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: In what units?  Do these numbers change as you zoom the workspace?

File: core/scratch_bubble.js [hunk 17]
```diff
@@ -0,0 +1,518 @@
+/**
+ * @license
+ * Visual Blocks Editor
+ *
+ * Copyright 2012 Google Inc.
```
Comment (rachel-fenichel) [inline core/scratch_bubble.js]: Fix date.

File: core/scratch_bubble.js [hunk 18]
```diff
@@ -0,0 +1,518 @@
...
+ * @param {!Element} content SVG content for the bubble.
+ * @param {!goog.math.Coordinate} anchorXY Absolute position of bubble's anchor
+ *     point.
+ * @param {?number} bubbleWidth Width of bubble, or null if not resizable.
+ * @param {?number} bubbleHeight Height of bubble, or null if not resizable.
+ * @param {?number} bubbleX X position of bubble
+ * @param {?number} bubbleY Y position of bubble
+ * @param {?boolean} minimized Whether or not this comment bubble is minimized
+ * (only the top bar displays), defaults to false if not provided.
+ * @constructor
```
Comment (rachel-fenichel) [inline core/scratch_bubble.js]: Needs an @extends annotation.

File: core/scratch_block_comment.js [hunk 19]
```diff
@@ -0,0 +1,404 @@
...
+ */
+Blockly.ScratchBlockComment.prototype.toggleMinimize_ = function() {
+  this.setMinimized(!this.isMinimized_);
+};
+
+/**
+ * Set the minimized state for this comment.
+ * @param {boolean} minimize Whether the comment should be minimized
+ */
+Blockly.ScratchBlockComment.prototype.setMinimized = function(minimize) {
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: You have setMinimized defined here and in ScratchBubble.  Is the version in ScratchBubble ever used?

File: core/scratch_bubble.js [hunk 20]
```diff
@@ -0,0 +1,518 @@
...
+ * @param {boolean} minimized Whether the bubble is minimized
+ * @return {!Element} The bubble's SVG group.
+ * @private
+ */
+Blockly.ScratchBubble.prototype.createDom_ = function(content, hasResize, minimized) {
+  this.bubbleGroup_ = Blockly.utils.createSvgElement('g', {}, null);
+  this.bubbleArrow_ = Blockly.utils.createSvgElement('line',
+      {'stroke-linecap': 'round'},
+      this.bubbleGroup_);
+  this.bubbleBack_ = Blockly.utils.createSvgElement('rect',
```
Comment (rachel-fenichel) [inline core/scratch_bubble.js:149]: Make as many of these chunks into helper functions as possible.

**Review by rachel-fenichel — COMMENTED** [review]
First pass of comments.  I'll have more after lunch.

File: core/scratch_block_comment.js (hunk 7 above)
Comment (kchadha) [reply core/scratch_block_comment.js]: These are allowed to be undefined because they are not strictly necessary for creating a comment.

A smart position will be chosen if x and y are not provided (based on the absolute position of the anchor on the block and the size of the stack that the block is part of). This is important for importing comments from 2.0 (during deserialization of scratch 2 projects, I'm relying on the auto layout by not passing comment positioning in the XML).

File: core/scratch_block_comment.js (hunk 8 above)
Comment (kchadha) [reply core/scratch_block_comment.js]: This is on the prototype because it's overriding the `SIZE` on the prototype of `Blockly.Icon`.

File: core/scratch_block_comment.js (hunk 19 above)
Comment (kchadha) [reply core/scratch_block_comment.js]: The version in ScratchBubble is used inside this function e.g.: `this.bubble_.setMinimized(true, this.getLabelText());`

File: core/scratch_block_comment.js (hunk 13 above)
Comment (kchadha) [reply core/scratch_block_comment.js:388]: Eek! Good catch.

File: core/block_render_svg_vertical.js (hunk 1 above)
Comment (kchadha) [reply core/block_render_svg_vertical.js:663]: RTL wasn't working for me in the vertical_playground so I wasn't able to test this, I still get this error on develop:

```
flyout_base.js:609 Uncaught TypeError: Cannot set property 'length' of undefined
    at Blockly.VerticalFlyout.Blockly.Flyout.recordCategoryScrollPositions_ (flyout_base.js:609)
    at Blockly.VerticalFlyout.getMetrics_ (flyout_vertical.js:211)
    at Blockly.WorkspaceSvg.getWidth (workspace_svg.js:830)
    at Object.Blockly.Xml.blockToDomWithXY (xml.js:86)
    at new Blockly.Events.Create (block_events.js:226)
    at Object.Blockly.Xml.domToBlock (xml.js:586)
    at Blockly.VerticalFlyout.Blockly.Flyout.show (flyout_base.js:506)
    at Blockly.Toolbox.showAll_ (toolbox.js:209)
    at Blockly.Toolbox.populate_ (toolbox.js:186)
    at Blockly.Toolbox.init (toolbox.js:135)
```

File: core/scratch_block_comment.js (hunk 16 above)
Comment (kchadha) [reply core/scratch_block_comment.js]: How should I refer to the units given that these numbers don't change as you zoom the workspace?

**Comment by kchadha** [comment]
@rachel-fenichel I think I've addressed all the PR comments you made yesterday or responded to the comments directly.

File: core/block_render_svg_vertical.js (hunk 1 above)
Comment (rachel-fenichel) [reply core/block_render_svg_vertical.js:663]: https://github.com/LLK/scratch-blocks/issues/1548

File: core/scratch_block_comment.js (hunk 9 above)
Comment (kchadha) [reply core/scratch_block_comment.js:110]: done.

File: core/scratch_block_comment.js (hunk 11 above)
Comment (kchadha) [reply core/scratch_block_comment.js:208]: done.

File: core/contextmenu.js [hunk 21]
```diff
@@ -408,12 +408,14 @@ Blockly.ContextMenu.wsExpandOption = function(hasCollapsedBlocks, topBlocks) {
  * Make a context menu option for deleting the current workspace comment.
  * @param {!Blockly.WorkspaceCommentSvg} comment The workspace comment where the
  *     right-click originated.
+ * @param {?string} optLabel An optional label for the comment. Defaults to
+ * Blockly.Msg.REMOVE_COMMENT
```
Comment (rachel-fenichel) [inline core/contextmenu.js]: Indent line continuation +4 spaces.

What else would this text be?  

It's the text of the context menu option, not the label for the comment.

File: core/scratch_block_comment.js [hunk 22]
```diff
@@ -0,0 +1,422 @@
...
+  if (this.block_.RTL) {
+    cursorX -= Blockly.BlockSvg.SEP_SPACE_X;
+  } else {
+    cursorX += width + Blockly.BlockSvg.SEP_SPACE_X;
+  }
+  return cursorX;
+};
+
+/**
+ * @typedef CommentContent The comment editor and label text to display in the
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: Does this typedef actually work?  It's different from this way of doing a typedef: https://github.com/google/closure-compiler/wiki/Using-JSDoc-Annotations-with-Closure-compiler#typedef

File: core/scratch_block_comment.js [hunk 23]
```diff
@@ -0,0 +1,422 @@
...
+};
+
+/**
+ * Get the truncated text for this comment to display in the minimized
+ * top bar.
+ * @return {string} The truncated comment text
+ */
+Blockly.ScratchBlockComment.prototype.getLabelText = function() {
+  if (this.text_.length > Blockly.ScratchBlockComment.MAX_LABEL_LENGTH) {
+    return this.text_.slice(0, Blockly.ScratchBlockComment.MAX_LABEL_LENGTH) + '\u2026';
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: Does this put the arrow in the right place in RTL?

File: core/scratch_bubble.js [hunk 24]
```diff
@@ -0,0 +1,544 @@
...
+  }
+
+  this.setAutoLayout(false);
+  this.moveTo(this.x, this.y);
+};
+goog.inherits(Blockly.ScratchBubble, Blockly.Bubble);
+
+/**
+ * Width of the border around the bubble.
+ */
```
Comment (rachel-fenichel) [inline core/scratch_bubble.js]: @package or @private on everything possible

File: core/scratch_bubble.js [hunk 25]
```diff
@@ -0,0 +1,544 @@
...
+        'y': (Blockly.ScratchBubble.TOP_BAR_HEIGHT / 2) + Blockly.ScratchBubble.BORDER_WIDTH,
+        'text-anchor': 'middle',
+        'dominant-baseline': 'middle'
+      }, this.bubbleGroup_);
+
+  this.labelTextNode_ = document.createTextNode(this.labelText_);
+  this.topBarLabel_.appendChild(this.labelTextNode_);
+};
+
+Blockly.ScratchBubble.prototype.createResizeHandle_ = function() {
```
Comment (rachel-fenichel) [inline core/scratch_bubble.js]: Missing documentation

File: core/xml.js [hunk 26]
```diff
@@ -265,6 +255,36 @@ Blockly.Xml.blockToDom = function(block, opt_noId) {
   return element;
 };
 
+/**
+ * Encode a ScratchBlockComment as XML.
+ * @param {!Blockly.ScratchBlockComment} block The block possibly containing
+ *     a comment to endcode.
```
Comment (rachel-fenichel) [inline core/xml.js]: endcode->encode

File: core/xml.js [hunk 27]
```diff
@@ -265,6 +255,36 @@ Blockly.Xml.blockToDom = function(block, opt_noId) {
...
+ * @param {!Element} element The XML element to which the comment should
+ *     encoding should be attached.
```
Comment (rachel-fenichel) [inline core/xml.js]: @private

**Review by rachel-fenichel — COMMENTED** [review]
Please test in RTL.

File: core/contextmenu.js (hunk 21 above)
Comment (kchadha) [reply core/contextmenu.js]: Yeah, I had originally changed that so that block comment context menu should read 'Delete' instead of 'Remove Comment', but then I realized that workspace comments should get the same context menu option label. Fixed.

**Comment by kchadha** [comment]
@rachel-fenichel, addressed the most recent comments!

Also, should this PR be blocked on the RTL regression fix, or is it okay if I file a separate issue for testing block comments in RTL and fixing up anything from this PR for RTL?

File: core/scratch_block_comment.js (hunk 16 above)
Comment (rachel-fenichel) [reply core/scratch_block_comment.js]: Workspace coordinates, or workspace units if there's no origin.

If they change as you zoom, they're usually pixel coordinates.

**Comment by rachel-fenichel** [comment]
My preference on RTL is that you try to fix the regression now so that you can test now.  Otherwise you're going to have to refamiliarize yourself with this code when debugging it, and in my experience things that get broken in RTL often just don't get fixed.

If it takes more than an hour or so to fix the RTL regression, then it might not be worth doing right now.  But it looks like it's pretty straightforward to debug.

**Comment by kchadha** [comment]
RTL issues resolved pending google/blockly#1896

File: core/scratch_block_comment.js [hunk 28]
```diff
@@ -242,17 +242,21 @@ Blockly.ScratchBlockComment.prototype.setVisible = function(visible) {
     // based on knowledge of the block that owns this comment:
     if (!this.x_ && this.x_ != 0 && !this.y_ && this.y_ != 0) {
       if (this.isMinimized_) {
-        this.x_ = this.iconXY_.x + 16;
+        this.x_ = this.block_.RTL ? this.iconXY_.x - 16 : this.iconXY_.x + 16;
```
Comment (rachel-fenichel) [inline core/scratch_block_comment.js]: These constants should be in terms of the GRID_UNIT.

**Comment by rachel-fenichel** [comment]
One more comment on magic numbers, and then lgtm.

**Review by rachel-fenichel — APPROVED** [review]
