### PR TITLE
Make insertion markers for define blocks have the correct width

### LINKED ISSUE #1186: Define block insertion marker is the wrong width
### Expected Behavior

Define block insertion marker should be the same width as the fully rendered define block, including the width of the internal block.

### Actual Behavior

image

### Steps to Reproduce

Disconnect the define block from everything else, then drag it near a stack of blocks.

### Operating System and Browser

All

### PR DESCRIPTION
**Pull request by ErikMejerHansen**
### Resolves

#1186 

### Proposed Changes

Make insertion markers for define blocks have to correct width. 

### Reason for Changes

Trying to fix #1186

### Test Coverage

No tests added

### CODE REVIEW

File: core/block_render_svg_vertical.js [hunk 1]
```diff
@@ -1606,7 +1606,8 @@ Blockly.BlockSvg.prototype.renderDefineBlock_ = function(steps, inputRows,
         input.connection.targetBlock().getHeightWidth().width +
         Blockly.BlockSvg.DEFINE_BLOCK_PADDING_RIGHT;
   } else {
-    rightSide = Blockly.BlockSvg.MIN_BLOCK_X_WITH_STATEMENT;
+    rightSide = Math.max(Blockly.BlockSvg.MIN_BLOCK_X_WITH_STATEMENT, rightSide)
```
Comment (rachel-fenichel) [inline core/block_render_svg_vertical.js:1610]: Add a comment that this case handles the block being rendered as an insertion marker (in all other cases there should be a target block connected on the statement input).

**Comment by picklesrus** [comment]
Thanks @ErikMejerHansen and @rachel-fenichel!
