### PR TITLE
Fix #968

### LINKED ISSUE #968: Text fields are the wrong colour
Left: actual behaviour.  Right: expected behaviour.
image

Directly caused by #962 
If a block doesn't have secondary and tertiary colours defined we darken the primary colour.  Blocks that use `Blockly.Colours.textField` seem to mostly just have a single colour defined, but are used as shadows.

A short-term fix is to revert #962.  

A better fix is to add a `colours_textfield` colour category and extension that uses the same colours for primary, secondary, and tertiary.  I'm not going to do that until #945 lands because #945 has a refactor of vertical_extensions.js, but it's easy to do once that's in.

### PR DESCRIPTION
**Pull request by rachel-fenichel**
### Resolves

#968 

### Proposed Changes

For blocks under blocks_common I'm adding secondary and tertiary colours explicitly.
In blocks_vertical/vertical_extensions.js I added an extension for setting text field colours.
For blocks under blocks_vertical I'm using that new extension.

I added an explicit error if colours are undefined.

### Reason for Changes

If blocks only have one colour defined Scratch-Blocks will darken that colour to get the secondary and tertiary colours, which makes text fields look terrible.

### Test Coverage

I checked that an extension is thrown when a single colour in a category or an entire category of colours is missing.
I loaded up scratch-gui to make sure that the built files work.

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
I'm using explicit colours instead of the new extension in blocks_common so I'm not calling in to blocks_vertical to create the common blocks.

Future question: should the extensions I've added all be in blocks_common instead?  Do they all apply to blocks regardless of whether they are oriented horizontally or vertically?

If yes, what should the namespace be?  `Blockly.ScratchBlocks.Extensions` is going to create even more confusion about what an extension is (scratch extensions vs blockly extensions).

**Comment by paulkaplan** [comment]
Yeah that naming could get confusing fast. Although, I _think_ the scratch version of extensions should be a transparent concept to scratch-blocks? On the other hand, if we go with a name like `BlockMixins` or something, it might also be confusing since at some point it will encounter the `Extensions` convention?

File: blocks_vertical/vertical_extensions.js [hunk 1]
```diff
@@ -151,6 +155,11 @@ Blockly.ScratchBlocks.VerticalExtensions.registerAll = function() {
     Blockly.Extensions.register('colours_' + name,
         Blockly.ScratchBlocks.VerticalExtensions.colourHelper(name));
   }
+
+  // Text fields transcend categories.
```
Comment (paulkaplan) [inline blocks_vertical/vertical_extensions.js:159]: transcend

**Review by paulkaplan — APPROVED** [review]
LG

**Comment by rachel-fenichel** [comment]
#980 for the followup question.


I agree that Scratch extensions shouldn't be conflicting with Blockly extensions in code, since scratch-blocks will just see Scratch extensions as normal blocks.  I do think there's a naming conflict because some of the same people will be building Scratch extensions and Scratch-Blocks extensions.
