### PR TITLE
Handling variable naming/renaming -- case sensitivity, and used name checking

### LINKED ISSUE #1008: Cannot open project with both "X" and "x" variables
### Expected Behavior

_Please describe what should happen_

Should be able to load a project like this one: https://llk.github.io/scratch-gui/develop/#189524895

### Actual Behavior

_Describe what actually happens_

It fails to load with this error: 

```
Uncaught (in promise) Error: Variable "X" is already in use and its id is "Q:(NMDNi+=uGHv?K1nO^-x" which conflicts with the passed in id, "Q:(NMDNi+=uGHv?K1nO^-X"
```

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

I made another repro with a simplified case: try to import a project with an uppercase and lowercase version of the same variable, like this one: 

image

https://llk.github.io/scratch-gui/develop/#191677809

---

Tracking down the root cause, it looks like scratch-blocks is lowercasing variable names to check for uniqueness. Scratch 2 has case-sensitive variable names, so I assume scratch 3 wants to also. We can create an issue on scratch-blocks once we confirm that we want that behavior and it'll be ok to fix it that way in scratch-blocks.

### LINKED ISSUE #1183: Incorrect "change" event when renaming variables
In the vertical playground, create a variable and drag the new "set <x> to <y>" block into the workspace. Open the dropdown and rename the variable to something else. 

There are two events, a `VarRename` and a `Change` for the variable field. The `VarRename` seems ok, it has the varId, oldName and newName. The `Change` event, though, doesn't look it has the right fields: the `oldValue` is the variable ID and the `newValue` is the new variable name. It looks like a confusion between the field value and the field name w/r/t variables, which is something that was changed to separate variable Ids and names. 

I believe this is the root cause of https://github.com/LLK/scratch-vm/issues/723

The change event is a problem because it is identical to the change event you get when changing to a different variable in the dropdown. In that case, `oldValue` and `newValue` are both variable IDs, so everything works.

### LINKED ISSUE #1292: "Used name" checking for variables should be case-insensitive
As noted in https://developers.google.com/blockly/guides/app-integration/best-practices#4_variable_and_function_names (h/t @mrjacobbloom), scratch differs from blockly in allowing variable names to be case sensitive.

### LINKED ISSUE #1343: Disallow renaming variables/lists to existing variable/list (resp.) names
### Expected Behavior

Should follow Scratch 2.0 behavior of disallowing variables to be renamed to existing variable names. Extend this behavior to lists as well.

### Actual Behavior

Currently, variables can be renamed to an existing variable name, conflating the two variables into one, and replacing all uses of the renamed variable to the existing name.

### Steps to Reproduce

Create a variable 'bar'.
Use it on the workspace.
Create a variable 'foo'.
Use it on the workspace.
Rename 'foo' to 'bar'.
Observe that all instances of 'foo' on the workspace now refer to 'bar', and 'foo' has been removed from the tool palette.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

### PR DESCRIPTION
**Pull request by kchadha**
### Resolves

Resolves #1292 
Resolves [scratch-gui#1008](https://github.com/LLK/scratch-gui/issues/1008)
Resolves #1343 
Resolves #1183

### Proposed Changes

Allows variables, lists, and broadcast messages to have case sensitive names. In the case of variables and lists, X and x are different names. In the case of broadcast messages, as in Scratch 2.0, users can create new messages with different capitalizations of the same message name  (e.g. 'message', 'mEssaGe', and 'Message' can all co-exist in the same broadcast message dropdown menu, but will all trigger the same 'when I receive' hats. This means that even though the dropdown has the three different capitalizations listed above, all of these name options refer to the same underlying message being broadcasted. This is consistent with the behavior of Scratch 2.0.

This PR also disallows renaming variables to the name of an existing variable. The previous behavior was to replace the variable being renamed with a reference to the existing variable that shares a name and type with the new name.

### Reason for Changes

The issues listed above, and backwards compatibility with scratch 2.0.

#1183 is closed by a combination of this PR and the variables_by_id work. This is explained in [this comment](https://github.com/LLK/scratch-blocks/issues/1183#issuecomment-359558583).

### Test Coverage

Tests have been modified to reflect new variable case sensitivity and the new rules about disallowing a variable to be renamed to an existing variable name.

#### Additional Notes

This work should be updated when the upstream [blockly issue#1537](https://github.com/google/blockly/issues/1537) is resolved. Validators for creating and renaming variables will move into their own separate functions to handle type-specific variable name validators.

### CODE REVIEW

File: core/variable_map.js [hunk 1]
```diff
@@ -74,10 +74,16 @@ Blockly.VariableMap.prototype.renameVariable = function(variable, newName) {
   Blockly.Events.setGroup(true);
   try {
     // The IDs may match if the rename is a simple case change (name1 -> Name1).
```
Comment (rachel-fenichel) [inline core/variable_map.js]: Delete this comment, since it's no longer relevant.

File: tests/jsunit/workspace_test.js [hunk 2]
```diff
@@ -235,8 +235,8 @@ function test_renameVariable_ReferenceExists() {
 }
 
 function test_renameVariable_TwoVariablesSameType() {
-  // Expect 'renameVariable' to change oldName variable name to newName.
-  // Expect oldName block name to change to newName
+  // Cannot rename variable to a name that already exists
```
Comment (rachel-fenichel) [inline tests/jsunit/workspace_test.js:238]: For these tests, add a note to each one to say that it's different from the behaviour in blockly.  It'll help us in the future.

**Review by rachel-fenichel — COMMENTED** [review]
Two changes then LGTM.

File: core/variable_map.js (hunk 1 above)
Comment (kchadha) [reply core/variable_map.js]: Done.

File: tests/jsunit/workspace_test.js (hunk 2 above)
Comment (kchadha) [reply tests/jsunit/workspace_test.js:238]: Done.

**Review by rachel-fenichel — APPROVED** [review]

**Review by paulkaplan — APPROVED** [review]
LGTM
