### PR TITLE
Fix switching variables via context menu 

### LINKED ISSUE #2944: Switching variable reference in context menu only changes appearance, doesn't actually update the variable reference
### Expected Behavior

Switching a variable reference using the variable reporter's context menu option should actually update the variable reference. 

### Actual Behavior

The variable reporter changes in appearance but still references the old variable it was referring to.
variable_refs

Found by a scratcher in the forums.

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_

Fixes https://github.com/LLK/scratch-gui/issues/2944

### Proposed Changes

_Describe what this Pull Request does_

Looks like this code was not updated when we moved from variable names to IDs. So just move the callback code to use IDs and `setValue` instead of names and `setText`

I was able to test this (after fixing the playground) by turning on the workspace event logging and noting that before this change, no "change" event was being emitted when the context menu was used. But after this change, the correct "change" event is emitted when using the context menu.

I also tested this by embedding it in the GUI and making sure the reported value from stack clicks was correct after switching variables.

### CODE REVIEW

File: core/variables.js [hunk 1]
```diff
@@ -299,6 +299,7 @@ Blockly.Variables.createVariable = function(workspace, opt_callback, opt_type) {
   // Prompt the user to enter a name for the variable
   Blockly.prompt(newMsg, '',
       function(text, additionalVars, variableOptions) {
+        variableOptions = variableOptions || {};
```
Comment (kchadha) [inline core/variables.js:302]: Thanks for fixing this! I probably didn't test the playground when making changes here for cloud variables.

**Review by kchadha — APPROVED** [review]
LGTM, thanks for fixing this!
