### PR TITLE
(Fixes #783) Check if block is real before checking if it's a shadow

### LINKED ISSUE #783: Opening dropdown in a block in the flyout and switching categories causes js error
When switching categories when a dropdown is open you get the following js error: 

vertical.js:2842 Uncaught TypeError: Cannot read property 'isShadow' of null
    at Blockly.FieldDropdown.onHide (vertical.js:2842)
    at Function.Blockly.DropDownDiv.hide (vertical.js:2462)
    at Blockly.Toolbox.<anonymous> (vertical.js:2973)
    at HTMLDivElement.g (vertical.js:2784)

### Steps to Reproduce
0. open js console.
1. Open motion category
2. Open dropdown in the "point toward" block
3. Without closing the dropdown , click on the "Events" category (probably others too).
4. see error.

### Operating System and Browser
Chrome MacOS

### PR DESCRIPTION
**Pull request by Tymewalk**
### Resolves

Issue #783 -  Opening dropdown in a block in the flyout and switching categories causes js error - [link](https://github.com/LLK/scratch-blocks/issues/783)

### Proposed Changes

This checks if `this.sourceBlock_` is real before checking `this.sourceBlock_.isShadow()`.

### Reason for Changes

This prevents the error `TypeError: this.sourceBlock_ is null`, which prevents the stage from being panned after it is triggered.

### Test Coverage

I don't see what tests are needed. Upon using `npm install` to recompile, doing the steps that would replicate the error instead work as intended.

### CODE REVIEW

**Comment by mrjacobbloom** [comment]
I'd usually prefer to format that as `this.sourceBlock_ && this.sourceBlock_.isShadow()` but your way should work too

**Comment by Tymewalk** [comment]
@Airhogs777 Your way also works and is more compact, so I've added it.

**Comment by Tymewalk** [comment]
@rschamp (Pinging you since you're the assignee)

With the recent commits, should I close this PR, re-apply my bugfix, and open a new PR? Or will merging this PR not cause any problems with those?

**Comment by rschamp** [comment]
@Tymewalk After we merge #791 there may be conflicts that prevent this PR from being automatically merged to develop. If there are no conflicts, then we can just merge it as-is. If there are conflicts, you don't have to close this PR, you can just merge develop into your branch and fix the conflicts, and then push your branch again. That will make this PR merge-able again.

**Comment by rschamp** [comment]
And I should add that we were holding off on merging other PRs to prevent additional conflicts being added to #791, since it is already so large.

**Comment by Tymewalk** [comment]
@rschamp All right, I'll keep an eye out for that. Thanks :smile: 

EDIT: Oh, it actually looks like #791 was merged already, and there's no conflicts. Lucky me

File: core/field_dropdown.js [hunk 1]
```diff
@@ -237,7 +237,7 @@ Blockly.FieldDropdown.prototype.onHide = function() {
   this.dropDownOpen_ = false;
   // Update colour to look selected.
   if (!this.disableColourChange_) {
-    if (this.sourceBlock_.isShadow()) {
+    if (this.sourceBlock_ && this.sourceBlock_.isShadow()) {
```
Comment (rachel-fenichel) [inline core/field_dropdown.js]: Hey there!

It looks like you want to check for this.sourceBlock_ one line higher:

```
if (!this.disableColourChange_ && this.sourceBlock_) {
  if (this.sourceBlock_isShadow()) ...
```

because sourceBlock_ is also used in the else if, and without a check for its existence.

Comment (Tymewalk) [reply core/field_dropdown.js]: @rachel-fenichel Oh, whoops! I'll fix that right away.

**Comment by Tymewalk** [comment]
I've moved the check one line higher, as requested by @rachel-fenichel.

**Comment by rachel-fenichel** [comment]
@rschamp looks good to me.

**Review by rschamp — APPROVED** [review]
Tested with scratch-gui and it looks great. Thanks @Tymewalk! And thank you @rachel-fenichel for reviewing.
