### PR TITLE
Fix the reported height of blocks with fields

### LINKED ISSUE #153: Toolbox scrollbar overlaps input fields
toolbox scrollbar

Steps to reproduce:
1. Open horizontal_playground.html
2. Select Pants tab.
3. Reduce window horizontal size until a scrollbar appears on the toolbox.

Expected behaviour:
- When selecting Pants tab, the toolbox becomes bigger to create margin under the input field.
- OR the toolbox becomes bigger when the scrollbar is rendered.

### PR DESCRIPTION
**Pull request by drigz**
These weren't taking their fields into account when calculating their
height. Fixes #153.

### CODE REVIEW

File: core/block_render_svg_horizontal.js [hunk 1]
```diff
@@ -603,3 +609,18 @@ Blockly.BlockSvg.prototype.renderDrawTop_ =
...
+ */
+Blockly.BlockSvg.prototype.getValueInput_ = function() {
+  for (var i = 0, child; child = this.childBlocks_[i]; i++) {
+    if (child.isShadow()) {
+      return child;
+    }
+  }
+
+  return null;
+}
```
Comment (rachel-fenichel) [inline core/block_render_svg_horizontal.js]: semicolon and newline

File: core/block_render_svg_horizontal.js [hunk 2]
```diff
@@ -603,3 +609,18 @@ Blockly.BlockSvg.prototype.renderDrawTop_ =
   }
   steps.push('z');
 };
+
+/**
+ * Get the field shadow block, if this block has one.
+ * @return {Blockly.BlockSvg} The field shadow block, or null if not found.
+ * @private
+ */
+Blockly.BlockSvg.prototype.getValueInput_ = function() {
```
Comment (rachel-fenichel) [inline core/block_render_svg_horizontal.js]: Are we guaranteed to only have one field per block?  This will work for now but we will probably have to come back to this for vertical scratch.

Add a comment that this is scratch-specific logic.

getValueInput is a misnomer (it's a block, not an input).  How about getFieldShadowBlock_()?

File: core/block_render_svg_horizontal.js (hunk 1 above)
Comment (drigz) [inline core/block_render_svg_horizontal.js]: Added the semicolon, thanks. What newline are you referring to?

File: core/block_render_svg_horizontal.js (hunk 2 above)
Comment (drigz) [inline core/block_render_svg_horizontal.js]: > Are we guaranteed to only have one field per block? This will work for now but we will probably have to come back to this for vertical scratch.

For horizontal, yes. For vertical, the [grammar](https://cloud.githubusercontent.com/assets/3409578/13230643/2c4b4518-d974-11e5-9765-9f8ef4e82efa.png) doesn't show fields being rendered outside the main block area, so this special case isn't necessary.

> getValueInput is a misnomer (it's a block, not an input). How about getFieldShadowBlock_()?

Thanks, I was unsure about the naming as different terms are used in different places.
