### PR TITLE
Set primary, secondary and tertiary colors on setValue

### LINKED ISSUE #986: The color picker didn't set to the color selected
### Expected Behavior

The color picker 'set pen color to ' block in pen catalog didn't reponse to the color selected

### Actual Behavior

It should, but the rounded color picker just keep red. It is interesting that argValues give the correct color value.

### Steps to Reproduce
Take a try at pen catalog from vertical playground.
http://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html

### Operating System and Browser

Windows 10 and chrome 58

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_

Fixes https://github.com/LLK/scratch-blocks/issues/986

### Proposed Changes

_Describe what this Pull Request does_

Changes the `setValue` function of the `FieldColour` to set all 3 colors (primary, secondary and tertiary) instead of just the primary color.

### Reason for Changes

_Explain why these changes should be made_

The secondary and tertiary colors are not used by the `FieldColour`, but the renderer expects to be able to use the secondary color as the fill for a shadow. See linked issue for more.

### CODE REVIEW

**Review by rachel-fenichel — APPROVED** [review]

File: core/field_colour.js [hunk 1]
```diff
@@ -106,11 +106,8 @@ Blockly.FieldColour.prototype.setValue = function(colour) {
   }
   this.colour_ = colour;
   if (this.sourceBlock_) {
-    this.sourceBlock_.setColour(
-      colour,
-      this.sourceBlock_.getColourSecondary(),
-      this.sourceBlock_.getColourTertiary()
-    );
+    // Set the primary, secondary and tertiary colour to this value.
```
Comment (rschamp) [inline core/field_colour.js:109]: Would you explain why here please? E.g. from the PR description
>  the renderer expects to be able to use the secondary color as the fill for a shadow.

**Review by rschamp — CHANGES_REQUESTED** [review]

File: core/field_colour.js (hunk 1 above)
Comment (paulkaplan) [reply core/field_colour.js:109]: @rschamp good idea 50db9134603bef71e130a911a9eb98a882cc4801
