### PR TITLE
Fix dragging out of flyout when workspace is zoomed

### LINKED ISSUE #150: Horizontal toolboxes place blocks in wrong location when workspace is scaled
Try on the multi-toolbox playground. Blocks are generated in the wrong place when the workspace is scaled. This seems to happen in all of the cases (RTL, LTR, top-attached, bottom-attached) although it's most noticeable in RTL.

@rachel-fenichel

### PR DESCRIPTION
**Pull request by rachel-fenichel**
Fixes #150

### CODE REVIEW

File: core/flyout.js [hunk 1]
```diff
@@ -896,6 +866,81 @@ Blockly.Flyout.prototype.createBlockFunc_ = function(originBlock) {
...
+ * Copy a block from the flyout to the workspace and position it correctly.
+ * @param {!Blockly.Block} originBlock The flyout block to copy.
+ * @param {!Blockly.Workspace} workspace The main workspace.
+ * @param {!Blockly.Flyout} flyout The flyout where originBlock originates.
+ * @return {!Blockly.Block} The new block in the main workspace.
+ * @private
+ */
+Blockly.Flyout.placeNewBlock_ = function(originBlock, workspace,
+    flyout) {
+  var svgRootOld = originBlock.getSvgRoot();
```
Comment (tmickel) [inline core/flyout.js]: I think let's call this blockSvgOld so to not confuse with the workspace SVG (same for svgRootNew)

File: core/flyout.js [hunk 2]
```diff
@@ -896,6 +866,81 @@ Blockly.Flyout.prototype.createBlockFunc_ = function(originBlock) {
...
+  // Figure out where the original block is on the screen, relative to the upper
+  // left corner of the main workspace.
+  var xyOld = Blockly.getSvgXY_(svgRootOld, workspace);
+  // Take into account that the flyout might have been scrolled horizontally
+  // (separately from the main workspace).
+  // Generally a no-op in vertical mode but likely to happen in horizontal
+  // mode.
+  var scrollX = flyout.workspace_.scrollX;
+  var scale = flyout.workspace_.scale;
+  xyOld.x += scrollX / scale - scrollX;
```
Comment (tmickel) [inline core/flyout.js:891]: Did you ever come around to figure out why these take the form of "scroll/scale - scroll"? I still don't really understand.
