### PR TITLE
Variables by Id -- Separate namespaces per variable type

### LINKED ISSUE #1245: Allow for renaming a message or list to an existing variable name.
### Expected Behavior

Messages can share names with variables and lists.
Lists and variables cannot share names.

### Actual Behavior

Currently messages cannot share names with lists and variables.

### Steps to Reproduce

One example of reproducing this error is to create a variable named "x", and then to create a message named "x". A modal pops up that says: 'A variable named "x" already exists.'

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

### Additional comments

Currently variables often get looked up by their names, and since messages are now internally modeled as variables, this will be a big change. We would need to either change variables to get looked up by their unique IDs, or when looking up variables, also ensure that type information matches.

### PR DESCRIPTION
**Pull request by kchadha**
### Resolves

Resolves #1245 

### Proposed Changes

This pull request introduces a major refactor of variables, making them unique by id or a combination of name and type. This allows variables of different types to share names.

The refactor is pulled in from upstream blockly, from the branch [blockly/variables_by_id](https://github.com/google/blockly/tree/variables_by_id) and more information about the change can be found there. These changes have been modified to work with scratch-blocks.

There are discussed issues that have been temporarily patched here, but will be later fixed upstream and replace the patches here.

#### Additional Notes
This change introduces the following warnings from scratch-gui when a variable or list is created, respectively:

```raven.js:55 Warning: Failed prop type: Invalid prop `value` of type `number` supplied to `MonitorComponent`, expected `string`.```

```raven.js:55 Warning: Failed prop type: Invalid prop `monitors` of type `OrderedMap` supplied to `MonitorList`, expected instance of `OrderedMap`.```

This is non-fatal, and is being tracked in [scratch-gui#1298](https://github.com/LLK/scratch-gui/issues/1298)

One additional issue introduced by this change is #1351, which has a proposed solution, but might need further discussion.

### Reason for Changes

#1245, and compatibility with SB2 projects.

### Test Coverage

Existing tests pass or have been modified according to introduced changes.

### CODE REVIEW

File: blocks_vertical/data.js [hunk 1]
```diff
@@ -544,7 +545,7 @@ Blockly.Constants.Data.RENAME_OPTION_CALLBACK_FACTORY = function(block) {
 Blockly.Constants.Data.DELETE_OPTION_CALLBACK_FACTORY = function(block) {
   return function() {
     var workspace = block.workspace;
-    var name = block.getField('VARIABLE').text_;
```
Comment (paulkaplan) [inline blocks_vertical/data.js:547]: We probably want this change above in RENAME_OPTION_CALLBACK_FACTORY also?

Not sure if this is the cause, but it seems that renaming doesn't work for the variable getter blocks, but does work for the variable dropdown blocks.

File: core/field_variable.js [hunk 2]
```diff
@@ -70,34 +82,48 @@ Blockly.FieldVariable.prototype.init = function() {
...
-    // variables to include in the dropdown.
-    this.sourceBlock_.workspace.createVariable(this.getValue(), this.variableType);
+  this.workspace_ = this.sourceBlock_.workspace;
+  // Using shorter name for this constant
+  var broadcastMsgType = Blockly.BROADCAST_MESSAGE_VARIABLE_TYPE;
+  var broadcastVars = this.workspace_.getVariablesOfType(broadcastMsgType);
+  if (this.workspace_.isFlyout && this.defaultType_ == broadcastMsgType &&
+      broadcastVars.length != 0) {
+    broadcastVars.sort(Blockly.VariableModel.compareByName);
+    this.setValue(broadcastVars[0].getId());
```
Comment (rachel-fenichel) [inline core/field_variable.js]: This setValue call also needs to be wrapped in an event enable/disable pair.

File: core/field_variable.js [hunk 3]
```diff
@@ -70,34 +82,48 @@ Blockly.FieldVariable.prototype.init = function() {
...
   }
-  // If the selected variable doesn't exist yet, create it.
-  // For instance, some blocks in the toolbox have variable dropdowns filled
-  // in by default.
-  if (!this.sourceBlock_.isInFlyout) {
-    // Check if there was exactly one element specified in the
-    // variableTypes list. This is the list that specifies which types of
-    // variables to include in the dropdown.
-    this.sourceBlock_.workspace.createVariable(this.getValue(), this.variableType);
+  this.workspace_ = this.sourceBlock_.workspace;
```
Comment (rachel-fenichel) [inline core/field_variable.js]: Move everything about checking if it's a braodcast msg + special case actions into a separate function and call it here.

File: core/field_variable.js [hunk 4]
```diff
@@ -228,54 +287,43 @@ Blockly.FieldVariable.dropdownCreate = function() {
...
-          thisField.setValue(newName);
+      var updateField = function(varId) {
+        if (varId) {
+          thisField.setValue(varId);
         }
       };
-      var broadcastMsgWkspc = workspace.isFlyout ? workspace.targetWorkspace : workspace;
-      Blockly.Variables.createVariable(broadcastMsgWkspc, setName, Blockly.BROADCAST_MESSAGE_VARIABLE_TYPE);
+      Blockly.Variables.createVariable(workspace, updateField,
+        Blockly.BROADCAST_MESSAGE_VARIABLE_TYPE);
```
Comment (rachel-fenichel) [inline core/field_variable.js]: Indent +2 more spaces

File: core/field_variable.js [hunk 5]
```diff
@@ -228,54 +287,43 @@ Blockly.FieldVariable.dropdownCreate = function() {
...
       return;
     }
 
-    // Call any validation function, and allow it to override.
-    itemText = this.callValidator(itemText);
-  }
-  if (itemText !== null) {
-    this.setValue(itemText);
+    // TODO (#1529): Call any validation function, and allow it to override.
```
Comment (rachel-fenichel) [inline core/field_variable.js]: Note that this is a blockly issue number, not a scratch-blocks issue number.

Comment (rachel-fenichel) [reply core/field_variable.js]: Same for any other issue numbers that point at the other repo.

File: core/field_variable_getter.js [hunk 6]
```diff
@@ -34,13 +34,26 @@ goog.require('Blockly.Field');
...
+ * @param {string} opt_varType The type of variable this field is associated with.
  * @extends {Blockly.FieldLabel}
  * @constructor
  *
  */
-Blockly.FieldVariableGetter = function(text, name) {
-  Blockly.FieldVariableGetter.superClass_.constructor.call(this, text);
+Blockly.FieldVariableGetter = function(text, name, opt_varType) {
+  this.size_ = new goog.math.Size(
+    Blockly.BlockSvg.FIELD_WIDTH,
```
Comment (rachel-fenichel) [inline core/field_variable_getter.js]: Indent +2 spaces.

Convention is indent +4 for continuations, per google's JS style guide.

File: core/field_variable_getter.js [hunk 7]
```diff
@@ -69,20 +82,62 @@ Blockly.FieldVariableGetter.prototype.init = function() {
...
+    return; // Initialization already happened.
   }
-  // If the selected variable doesn't exist yet, create it.
-  // For instance, some blocks in the toolbox have variable dropdowns filled
-  // in by default.
-  if (!this.sourceBlock_.isInFlyout) {
-    this.sourceBlock_.workspace.createVariable(this.getValue());
+  this.workspace_ = this.sourceBlock_.workspace;
+  var variable = Blockly.Variables.getOrCreateVariablePackage(
+    this.workspace_, null, this.text_, this.variableType_);
```
Comment (rachel-fenichel) [inline core/field_variable_getter.js]: Indent +2 spaces.

**Review by rachel-fenichel — COMMENTED** [review]
Partial comments.  I'm up to `realizePotentialVar`.

Please fix indentation throughout.

File: blocks_vertical/data.js (hunk 1 above)
Comment (kchadha) [reply blocks_vertical/data.js:547]: Fixed the renaming problem. This wasn't the issue, but I changed it to match DEFAULT_OPTION_CALLBACK_FACTORY for good measure.

File: core/field_variable.js (hunk 3 above)
Comment (kchadha) [reply core/field_variable.js]: Done.

File: core/field_variable.js (hunk 2 above)
Comment (kchadha) [reply core/field_variable.js]: No longer relevant because of the way I refactored this code.

File: core/field_variable.js (hunk 4 above)
Comment (kchadha) [reply core/field_variable.js]: Done.

File: core/field_variable.js (hunk 5 above)
Comment (kchadha) [reply core/field_variable.js]: Done. Will look for more.

File: core/field_variable_getter.js (hunk 6 above)
Comment (kchadha) [reply core/field_variable_getter.js]: Done.

File: core/field_variable_getter.js (hunk 7 above)
Comment (kchadha) [reply core/field_variable_getter.js]: Done.

File: core/variables.js [hunk 8]
```diff
@@ -163,12 +195,75 @@ Blockly.Variables.generateUniqueName = function(workspace) {
   return newName;
 };
 
+/**
+ * Remove any possiblity of conflict/duplication between a real and potential variable.
```
Comment (rachel-fenichel) [inline core/variables.js:199]: For all of these comments on `realizePotentialVar`, feel free to fix them in a second PR if that's easier.

File: core/variables.js [hunk 9]
```diff
@@ -163,12 +195,75 @@ Blockly.Variables.generateUniqueName = function(workspace) {
...
+ * and returns the real var.
+ * If a potential var exists and a real var does not exist (or 'opt_realWkspc'
+ * was not provided), creates the potential var as a real var,
+ * discards the potential var, and returns the newly created real var.
+ * If a potential var does not exist, returns null.
+ *
+ * @param {string} varName The name of the variable to check for.
+ * @param {string} varType The type of the variable to check for.
+ * @param {!Blockly.Workspace} potentialVarWkspc The workspace containing the
+ * potential vraible map we want to check against.
```
Comment (rachel-fenichel) [inline core/variables.js]: Indent line continuations +4 spaces in param/return annotations.
Fix spelling of "variable".

is there a reason to pass in the main workspace, instead of just getting the target workspace from the `potentialVarWkspc`?  It would be nice to get rid of the optional argument.

Generally the short form of `workspace` is `ws` in our code, rather than `wkspc`.

File: core/variables.js [hunk 10]
```diff
@@ -163,12 +195,75 @@ Blockly.Variables.generateUniqueName = function(workspace) {
...
+ * @param {?Blockly.Workspace} opt_realWkspc An optional real workspace to check
+ * against.
+ * @return {?Blockly.VariableModel} The matching variable, if one already existed
+ * in the real workspace or the newly transformed variable, if one already
+ * existed as a potential variable. Null if no matching varaiable, real or
```
Comment (rachel-fenichel) [inline core/variables.js]: Fix spelling of variable here as well.

File: core/variables.js [hunk 11]
```diff
@@ -163,12 +195,75 @@ Blockly.Variables.generateUniqueName = function(workspace) {
...
+ * potential, was found.
+ */
+Blockly.Variables.realizePotentialVar = function(varName, varType, potentialVarWkspc,
+  opt_realWkspc) {
```
Comment (rachel-fenichel) [inline core/variables.js]: Indent +2 spaces.

File: core/variables.js [hunk 12]
```diff
@@ -163,12 +195,75 @@ Blockly.Variables.generateUniqueName = function(workspace) {
...
+  var potentialVarMap = potentialVarWkspc.getPotentialVariableMap();
+  if (potentialVarMap == null) {
+    console.warn('Called Blockly.Variables.realizePotentialVar with incorrect ' +
+      'workspace. The provided workspace does not have a potential variable map.');
```
Comment (rachel-fenichel) [inline core/variables.js]: Indent +2 spaces.

File: core/variables.js [hunk 13]
```diff
@@ -163,12 +195,75 @@ Blockly.Variables.generateUniqueName = function(workspace) {
...
+ * against.
+ * @return {?Blockly.VariableModel} The matching variable, if one already existed
+ * in the real workspace or the newly transformed variable, if one already
+ * existed as a potential variable. Null if no matching varaiable, real or
+ * potential, was found.
+ */
+Blockly.Variables.realizePotentialVar = function(varName, varType, potentialVarWkspc,
+  opt_realWkspc) {
+  var potentialVarMap = potentialVarWkspc.getPotentialVariableMap();
+  if (potentialVarMap == null) {
```
Comment (rachel-fenichel) [inline core/variables.js]: `if (!potentialVarMap)`

File: core/variables.js [hunk 14]
```diff
@@ -163,12 +195,75 @@ Blockly.Variables.generateUniqueName = function(workspace) {
...
+  }
+  // First check if a variable with the same name and type already exists as a
+  // real variable.
+  var realVar;
+  if (opt_realWkspc) {
+    realVar = Blockly.Variables.getVariable(opt_realWkspc, null, varName, varType);
+  }
+  var sharesNameWithPotentialVar = false;
+  var potentialVars = potentialVarMap.getVariablesOfType(varType);
+  for (var i=0, potentialVar = potentialVars[i]; i < potentialVars.length; i++) {
```
Comment (rachel-fenichel) [inline core/variables.js]: spaces around `=`

File: core/variables.js [hunk 15]
```diff
@@ -163,12 +195,75 @@ Blockly.Variables.generateUniqueName = function(workspace) {
...
+    return;
+  }
+  // First check if a variable with the same name and type already exists as a
+  // real variable.
+  var realVar;
+  if (opt_realWkspc) {
+    realVar = Blockly.Variables.getVariable(opt_realWkspc, null, varName, varType);
+  }
+  var sharesNameWithPotentialVar = false;
+  var potentialVars = potentialVarMap.getVariablesOfType(varType);
```
Comment (rachel-fenichel) [inline core/variables.js]: Why this loop instead of just calling `potentialVarMap.getVariable(varName, varType)`?

File: core/variables.js [hunk 16]
```diff
@@ -163,12 +195,75 @@ Blockly.Variables.generateUniqueName = function(workspace) {
...
+  for (var i=0, potentialVar = potentialVars[i]; i < potentialVars.length; i++) {
+    // TODO (#1292) case sensitivity check based on var type
+    if (varName == potentialVar.name) {
+      sharesNameWithPotentialVar = true;
+      break;
+    }
+  }
+  var variable;
+  if (sharesNameWithPotentialVar) {
```
Comment (rachel-fenichel) [inline core/variables.js]: Flip this around:
```
if (!sharesNameWithPotentialVar) { 
  return null;
}
var id = potentialVar.getId();
potentialVarMap.deleteVariable(potentialVar);
if (realVar) {
  return realVar;
}
return potentialVar.targetWorkspace.createVariable(id, varName, varType);
```

You don't need to call `getOrCreateVariablePackage` because at this point you know that you are creating the variable, not getting ti.

**Comment by paulkaplan** [comment]
Commit 73f55ee9a89e3d933eea509ea275a54787813adf actually points to a problem in the VM, where the blocks are not being updated when the var rename event is received. The variable model in the VM is being updated, which is what writes the `<variables>` xml that blockly receives on workspace update, but the actual block xml still has the old variable name in it. I think we'll need to go through the blocks list and change the values for the variable names in the VM to really solve that problem?

**Comment by kchadha** [comment]
@paulkaplan tracking this in [scratch-vm#909](https://github.com/LLK/scratch-vm/issues/909), though it seems like it could be a duplicate of [scratch-vm#723](https://github.com/LLK/scratch-vm/issues/723)...?

File: core/variables.js (hunk 8 above)
Comment (kchadha) [reply core/variables.js:199]: Did it in this PR.

File: core/variables.js (hunk 9 above)
Comment (kchadha) [reply core/variables.js]: Done.

File: core/variables.js (hunk 15 above)
Comment (kchadha) [reply core/variables.js]: Done.

File: core/variables.js (hunk 16 above)
Comment (kchadha) [reply core/variables.js]: Done.

**Comment by paulkaplan** [comment]
Cool. Changes LG to me. Obviously lots of them though, so let's make sure to get some internal testing on the calendar once this is merged.

**Comment by rachel-fenichel** [comment]
LGTM!
