### PR TITLE
Variable modal messages

### LINKED ISSUE #1244: Modify messages for create variable modal (for variables, lists, and broadcast messages)
### Expected Behavior

The message in the modal that appears when creating a variable, list, or broadcast message should change depending on what is being created.

### Actual Behavior

Currently, the message for creating variables, messages, and lists all say: "New variable name:".

### Steps to Reproduce
Create a new messsage via the field dropdown in any of the broadcast message blocks.
Create a new list via the "Create list..." button.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

### PR DESCRIPTION
**Pull request by kchadha**
### Resolves

Resolves #1244.

### Proposed Changes

Changes message in the modal that appears when creating a variable, list, or broadcast message to reflect the thing that is being created (instead of 'New variable name' for all of them).

Minor refactoring of code that used hard coded 'list' to refer to the list variable type. This existing code (and new changes) both use new `Blockly.LIST_VARIABLE_TYPE` constant.

Changed name of `Blockly.BROADCAST_MESSAGE_TYPE` to `Blockly.BROADCAST_MESSAGE_VARIABLE_TYPE` to match new, more specific naming convention for variable type constants (e.g. `LIST_VARIABLE_TYPE`).

### Reason for Changes

Current behavior was that creating a new message or list would bring up a modal that asks the user to enter a 'New variable name'.

### Test Coverage

Existing tests pass.

### CODE REVIEW

**Comment by thisandagain** [comment]
🎉  @kchadha would you mind resolving the conflict in `core/constants.js`?

**Review by paulkaplan — APPROVED** [review]
LGTM

File: core/variables.js [hunk 1]
```diff
@@ -173,13 +173,19 @@ Blockly.Variables.generateUniqueName = function(workspace) {
...
 Blockly.Variables.createVariable = function(workspace, opt_callback, opt_type) {
-  // (karishma) TODO (#1244) Modal message should change depending on what type
-  // (opt_type above) of variable we are creating. If opt_type is not provided,
-  // we should default to the original 'NEW_VARIABLE_TITLE' message for
-  // scalar variables.
+  // Decide on a modal message based on the opt_type. If opt_type was not
+  // provided, default to the original message for scalar variables.
+  var newMsg = '';
+  if (opt_type === 'list') {
+    newMsg = Blockly.Msg.NEW_LIST_TITLE;
```
Comment (rachel-fenichel) [inline core/variables.js]: 'list' should be a constant, and 'broadcast_msg' already is.

Comment (kchadha) [reply core/variables.js]: done.

**Review by rachel-fenichel — APPROVED** [review]
