### PR TITLE
Use variable field directly instead of shadow

### LINKED ISSUE #942: Field Variable Dropdowns are shadows
### Expected Behavior

Variable dropdown should be a field of the main block, it should not be a shadow.

### Actual Behavior

When I drag a block into the variable dropdown, it replaces the variable dropdown.
This is a problem because when I try to delete the variable in this state, the variable is recreated when the operator is removed because the main block recreates the shadow and its variable described in the ShadowDom.

### Steps to Reproduce
Create a Variable.
screenshot from 2017-06-13 10 32 55

Cover the field variable dropdown with an operator block.
screenshot from 2017-06-13 10 33 25

### Operating System and Browser

Ubuntu Chrome Version  59.0.3071.86

### PR DESCRIPTION
**Pull request by paulkaplan**
### Resolves

_What Github issue does this resolve (please include link)?_

Fixes https://github.com/LLK/scratch-blocks/issues/942
### Proposed Changes

_Describe what this Pull Request does_

### Reason for Changes

Uses a field instead of an input + shadow for the variable dropdown

_Explain why these changes should be made_
https://github.com/LLK/scratch-blocks/issues/942

Along with https://github.com/LLK/scratch-vm/pull/608, this works with importing projects as well. Here is what it looks like:

image

vs what it used to be (circular inputs)

image

### CODE REVIEW

File: core/variables.js [hunk 1]
```diff
@@ -234,26 +234,19 @@ Blockly.Variables.createShadowDom_ = function(type) {
...
 Blockly.Variables.createVariableDom_ = function(variableModel) {
-  //   <value name="VARIABLE">
-  //     <shadow type="data_variablemenu">
-  //       <field name="VARIABLE">variablename
-  //       </field>
-  //     </shadow>
-  //   </value>
-  var value = Blockly.Variables.createValueDom_('VARIABLE');
-  var shadow = Blockly.Variables.createShadowDom_('data_variablemenu');
+  // <field name="VARIABLE">
```
Comment (rachel-fenichel) [inline core/variables.js:242]: Based on line 247-8 this is incomplete.

Comment (rachel-fenichel) [reply core/variables.js:242]: Actually, this is a problem throughout the file, so I've recorded it in #949

**Review by rachel-fenichel — APPROVED** [review]
LGTM.
